[project]
name = "beerdin-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "pre-commit>=4.1.0",
    "ruff>=0.9.6",
]
